{
 "title": "UPS Status",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Battery Capacity",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_battery_capacity" }
   ]
  },
  {
   "title": "UPS Load ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "ups_load", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 5, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "ups_out_voltage", "legendFormat": "{{device}}" }
   ]
  },
  {
   "title": "Misc status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "targets": [
    { "expr": "ups_state", "legendFormat": "ups-state" },
    { "expr": "ups_test_result", "legendFormat": "test_result" }
   ]
  }
 ]
}